### ISSUE TITLE
IntAlphabet in automata assignment

### ISSUE THREAD

**Issue by vhavlena** [vhavlena/z3#40]
It seems there is a fishy thing in automata assignment. For some input `slog_stranger_64_sink.smt2`, we get in the preprocessing automata assignment containing an `Mata::NFA` having `IntAlphabet` as an alphabet. If we then call `AutAssignment::update_alphabet` we get an exception, since `get_alphabet_symbols` is not defined for `IntAlphabet`. I think `IntAlphabet` should not be used for automata in an automata assignment.

**Comment by Adda0** [comment]
You are right that it should not be used. If we are using IntAlphabet anywhere in AutAssignment, it is a mistake and it should be replaced with OnTheFlyAlphabet.

**Comment by vhavlena** [comment]
Right, can you take a look at it please? In particular, we should get know how these alphabets get into the assignment.
